### ISSUE TITLE
Not working in Chrome 39.0.2171.99 m

### ISSUE THREAD

**Issue by pranitakale** [jgoulah/webrecorder#3]
Uncaught TypeError: undefined is not a function on line no.174
